import poolImg from '../../../assets/gallery_pool.png';
import bedroomImg from '../../../assets/gallery_bedroom.png';
import opulenceImg from '../../../assets/listing_opulence.png';
import harmonyImg from '../../../assets/listing_harmony.png';
import prestigeImg from '../../../assets/listing_prestige.png';
import heroImg from '../../../assets/luxury_estate_hero.png';

const propertyData = [
    {
        id: 1,
        title: 'The Azure Villa',
        subtitle: 'Coastal Luxury',
        location: 'Malibu, California',
        price: '$24,500,000',
        area: '8,400 sq ft',
        beds: 6,
        baths: 8,
        yearBuilt: 2022,
        status: 'For Sale',
        heroImage: poolImg,
        description: 'Perched along the most coveted stretch of Malibu coastline, The Azure Villa is an architectural triumph that marries raw natural beauty with refined modern living. Floor-to-ceiling glass walls dissolve the boundary between interior and the Pacific Ocean, while the zero-edge infinity pool appears to float seamlessly into the horizon. Crafted by Pritzker Prize–winning architects, every room commands sweeping ocean views and fills with the golden light of coastal California.',
        features: ['Infinity Pool', 'Private Beach Access', 'Smart Home System', 'Home Theater', 'Wine Cellar', "Chef's Kitchen", 'Rooftop Terrace', 'Heated Floors'],
        galleryImages: [poolImg, bedroomImg, opulenceImg, harmonyImg, prestigeImg, heroImg],
    },
    {
        id: 2,
        title: 'Opulence Estate',
        subtitle: 'Historic Grandeur',
        location: 'Beverly Hills, California',
        price: '$38,000,000',
        area: '16,200 sq ft',
        beds: 9,
        baths: 12,
        yearBuilt: 1938,
        status: 'For Sale',
        heroImage: opulenceImg,
        description: "A storied landmark of Beverly Hills, the Opulence Estate stands as a testament to the golden era of Hollywood architecture. Originally commissioned by a silver screen legend, this palatial residence has been meticulously restored to preserve its original grandeur while integrating every modern luxury. Manicured grounds spanning two acres frame the estate's stately colonnaded facade, while inside, soaring coffered ceilings and original parquetry floors continue to inspire awe.",
        features: ['Historic Registry Landmark', 'Grand Ballroom', 'Championship Tennis Court', 'Olympic Pool', 'Staff Quarters', 'Guard House', 'Motor Court', 'Formal Gardens'],
        galleryImages: [opulenceImg, heroImg, poolImg, prestigeImg, bedroomImg, harmonyImg],
    },
    {
        id: 3,
        title: 'Serenity Heights',
        subtitle: 'Mountain Escape',
        location: 'Aspen, Colorado',
        price: '$15,750,000',
        area: '7,800 sq ft',
        beds: 5,
        baths: 6,
        yearBuilt: 2020,
        status: 'For Sale',
        heroImage: bedroomImg,
        description: 'Hidden above the clouds at 9,200 feet elevation, Serenity Heights is a sanctuary of silence and sustainable luxury. This off-grid-capable retreat harvests its own energy through state-of-the-art solar arrays and geothermal systems, producing more than it consumes. Expansive Douglas fir beams and locally quarried stone roots the residence in its alpine landscape, while panoramic triple-glazed windows frame a cathedral of snow-capped summits stretching to the horizon.',
        features: ['Off-Grid Capable', 'Geothermal Heating', 'Solar Array', 'Ski-in/Ski-out', 'Sauna & Hot Tub', 'Mountain Views', 'Heated Driveway', 'EV Charging'],
        galleryImages: [bedroomImg, harmonyImg, prestigeImg, opulenceImg, poolImg, heroImg],
    },
    {
        id: 4,
        title: 'Prestige Manor',
        subtitle: 'Urban Sophistication',
        location: 'Manhattan, New York',
        price: '$42,000,000',
        area: '10,500 sq ft',
        beds: 7,
        baths: 9,
        yearBuilt: 2019,
        status: 'For Sale',
        heroImage: prestigeImg,
        description: "Commanding the entire 68th floor of one of Manhattan's most iconic towers, Prestige Manor redefines what it means to live above it all. A private elevator opens directly into a residence where Central Park, the Hudson River, and the glittering skyline converge in a single unobstructed panorama. Designed by the world's most sought-after interior atelier, the residence features hand-laid alabaster walls, bespoke furnishings, and a private 2,000-bottle wine vault.",
        features: ['Full Floor Private', 'Concierge Service', 'Private Elevator', 'Skyline Views', 'Wine Vault', 'Fitness Center', 'Doorman Building', 'Rooftop Access'],
        galleryImages: [prestigeImg, opulenceImg, heroImg, poolImg, bedroomImg, harmonyImg],
    },
    {
        id: 5,
        title: 'Harmony Home',
        subtitle: 'Eco-Friendly Living',
        location: 'Sonoma, California',
        price: '$8,900,000',
        area: '5,200 sq ft',
        beds: 4,
        baths: 5,
        yearBuilt: 2023,
        status: 'For Sale',
        heroImage: harmonyImg,
        description: 'Nestled among the rolling vineyards of Sonoma Valley, Harmony Home is the pinnacle of mindful luxury. A Green ARK Signature property, it achieves net-zero energy through a photovoltaic roof integrated into its award-winning design. Living roofs populated with native flora, rainwater reclamation, and a fully operational organic farm on the property prove that sustainability and opulence are not opposing forces, but complementary ones.',
        features: ['Net-Zero Energy', 'Living Roof', 'Organic Farm', 'Rainwater Reclamation', 'Vineyard Views', 'Guest Cottage', 'Outdoor Kitchen', 'Bocce Court'],
        galleryImages: [harmonyImg, poolImg, bedroomImg, heroImg, opulenceImg, prestigeImg],
    },
    {
        id: 6,
        title: 'Legacy Ranch',
        subtitle: 'Countryside Estate',
        location: 'Hill Country, Texas',
        price: '$18,200,000',
        area: '22,000+ Acres',
        beds: 8,
        baths: 10,
        yearBuilt: 2015,
        status: 'For Sale',
        heroImage: heroImg,
        description: 'Spread across 22,000 pristine acres of Texas Hill Country, Legacy Ranch is more than a property — it is a legacy. The main residence, a masterwork of Texas vernacular architecture, anchors a self-sufficient compound that includes a working cattle operation, a private lake stocked with trophy bass, and a regulation-sized equestrian facility. Clear dark skies perfect for stargazing crown land that has been lovingly stewarded for generations.',
        features: ['22,000 Acres', 'Private Lake', 'Equestrian Facility', 'Working Cattle Ranch', 'Dark Sky Reserve', 'Guest Lodge', 'Hunting & Fishing', 'Helicopter Pad'],
        galleryImages: [heroImg, opulenceImg, harmonyImg, poolImg, prestigeImg, bedroomImg],
    },
    {
        id: 7,
        title: 'The Vertex',
        subtitle: 'Modern Penthouse',
        location: 'Miami, Florida',
        price: '$31,000,000',
        area: '9,800 sq ft',
        beds: 5,
        baths: 7,
        yearBuilt: 2024,
        status: 'Coming Soon',
        heroImage: harmonyImg,
        description: "The Vertex crowns Miami's newest architectural icon — a crystalline tower rising 850 feet above Biscayne Bay. This sky-high penthouse features a wraparound terrace with a private pool overlooking the Miami skyline, the Atlantic Ocean, and the Everglades. Fully integrated smart-home technology by Crestron controls every system from a single interface, while the building's AI-powered amenities include a wellness center, private cinema, and a curated art gallery lobby.",
        features: ['Private Rooftop Pool', 'Wraparound Terrace', 'Ocean & City Views', 'Crestron Smart Home', 'Private Cinema', 'AI Concierge', 'Yacht Dock Access', 'Helipad'],
        galleryImages: [harmonyImg, bedroomImg, poolImg, prestigeImg, heroImg, opulenceImg],
    },
    {
        id: 8,
        title: 'Golden Sands',
        subtitle: 'Beachfront Paradise',
        location: 'Palm Beach, Florida',
        price: '$27,500,000',
        area: '11,000 sq ft',
        beds: 7,
        baths: 9,
        yearBuilt: 2021,
        status: 'For Sale',
        heroImage: opulenceImg,
        description: "Commanding 300 feet of pristine Palm Beach oceanfront, Golden Sands is the quintessential expression of Florida estate living. Private dunes frame a residence that channels the warmth of Mediterranean architecture through its coral stone facades, arched loggia, and sun-drenched courtyards. The resort-style grounds include a full beach club with cabanas, a professional pickleball court, and a spa pavilion, all attended by a full-time estate staff.",
        features: ['300ft Ocean Frontage', 'Private Beach Club', 'Spa Pavilion', 'Pickleball Court', 'Full Staff Quarters', "Chef's Kitchen", 'Coral Stone Detail', 'Fruit Orchard'],
        galleryImages: [opulenceImg, poolImg, heroImg, harmonyImg, bedroomImg, prestigeImg],
    },
];

export default propertyData;
